### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by ghost** [1234filip/PublicLoader#1]
I never touched web and server stuff, but today I was trying something, 
created localserver and so on, on windows machine. 

When I open
http://localhost/WebPanel/login.php
There is error on top
**ERROR: could not find driver**
and same when I login.

What it actually mean?

**Comment by filiptrplan** [comment]
Can you please post your php error log? Also can you please tell me what web server are you using and which OS is it running on? I'm sorry for the slow response

**Comment by filiptrplan** [comment]
closed as there was no response
