### ISSUE TITLE
Login is broken

### ISSUE THREAD

**Issue by japped** [1234filip/PublicLoader#3]
when i try to login with username `admin` and password `admin` it says "Password is invalid"

**Comment by filiptrplan** [comment]
This project is 2 years old at this point. I'm amazed you even found it. I won't be providing bug fixes or support for the current version. Version 3.0 is coming sometime by the end of this year, so just follow this repo for any updates. I wish you luck with fixing the issue. 

It is very likely that you forgot to execute the `db.sql` file.

**Comment by SchuhmacherAndre** [comment]
I'm very late, but the webpanel is still 100% functional.

**Comment by japped** [comment]
Nope

**Comment by SchuhmacherAndre** [comment]
As filip said, you probably did not import the db.sql file, because the panel is functioning correctly for me.

**Comment by filiptrplan** [comment]
This is a really old project. I will probably start working on a v3 at the end of this year because I've been busy with other projects. No more issues.

**Comment by japped** [comment]
> As filip said, you probably did not import the db.sql file, because the panel is functioning correctly for me.

I did everything but username admin and pass admin is incorrect when i try

**Comment by japped** [comment]
> This is a really old project. I will probably start working on a v3 at the end of this year because I've been busy with other projects. No more issues.

Yey
